export const TOOLS = [{
    id: 'git',
    name: 'git'
}, {
    id: 'terraform',
    name: 'terraform'
}, {
    id: 'docker',
    name: 'Docker'
}, {
    id: 'postman-img',
    name: 'Postman'
}, {
    id: 'jira',
    name: 'jira'
}, {
    id: 'nginx',
    name: 'nginx'
}, {
    id: 'androidstudio',
    name: 'androidstudio'
}, {
    id: 'xcode',
    name: 'xcode'
}, {
    id: 'figma',
    name: 'figma'
}, {
    id: 'gradle',
    name: 'gradle'
}]